fix: Fix packaging
Including the direct download URL in setup.py caused it to be rejected
by PyPI:

  HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
  Invalid value for requires_dist. Error: Can't have direct dependency: "ctds @ https:// ...